[package]
name = "{{project-name}}-api"
version = "0.1.0"
authors = ["{{author}}"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
{{project-deps}}
